//! Check command - validates project configuration, queries, and generated Rust code.

use crate::commands::build;
use crate::metrics_sender::MetricsSender;
use crate::output::{Operation, Step};
use crate::project::ProjectContext;
use crate::utils::sparrowc_utils::{
    analyze_source, collect_hx_files, generate_content, parse_content,
};
use crate::utils::{print_error, print_warning};
use eyre::Result;
use std::fs;
use std::path::Path;
use std::time::Instant;
use tokio::process::Command;

/// Output from running cargo check.
struct CargoCheckOutput {
    success: bool,
    #[allow(dead_code)] // May be useful for debugging
    full_output: String,
    errors_only: String,
}

const VERSION_STAMP_PREFIX: &str = "// generated by sparrow ";

/// Prepend the 3-line version stamp header to a code string.
fn prepend_version_stamp(code: &str) -> String {
    let hash = env!("SPARROW_BUILD_HASH");
    format!(
        "// generated by sparrow {hash}\n\
         // sparrow-core workspace: {hash}\n\
         // Do not edit — regenerate with `sparrow check`\n\
         {code}",
    )
}

/// Read the hash from an existing queries.rs file's first line, if present.
/// Returns `None` if the file doesn't exist or has no version stamp.
fn read_existing_stamp_hash(queries_rs: &std::path::Path) -> Option<String> {
    let content = std::fs::read_to_string(queries_rs).ok()?;
    let first_line = content.lines().next()?;
    let hash = first_line.strip_prefix(VERSION_STAMP_PREFIX)?;
    Some(hash.trim().to_string())
}

/// Public wrapper for use by `sparrow doctor`.
#[allow(dead_code)]
pub fn read_existing_stamp_hash_pub(queries_rs: &std::path::Path) -> Option<String> {
    read_existing_stamp_hash(queries_rs)
}

pub async fn run(
    instance: Option<String>,
    metrics_sender: &MetricsSender,
    debug_codegen: bool,
) -> Result<()> {
    // Load project context
    let project = ProjectContext::find_and_load(None)?;

    match instance {
        Some(instance_name) => check_instance(&project, &instance_name, metrics_sender, debug_codegen).await,
        None => check_all_instances(&project, metrics_sender, debug_codegen).await,
    }
}

async fn check_instance(
    project: &ProjectContext,
    instance_name: &str,
    metrics_sender: &MetricsSender,
    debug_codegen: bool,
) -> Result<()> {
    let start_time = Instant::now();
    let op = Operation::new("Checking", instance_name);

    // Validate instance exists in config
    let _instance_config = project.config.get_instance(instance_name)?;

    // ── Version stamp comparison ──────────────────────────────────────────
    let instance_workspace = project.instance_workspace(instance_name);
    let final_queries_rs = instance_workspace.join("sparrow-container/src/queries.rs");

    let binary_hash = env!("SPARROW_BUILD_HASH");
    if binary_hash != "unknown" {
        if let Some(existing_hash) = read_existing_stamp_hash(&final_queries_rs) {
            if existing_hash != binary_hash {
                print_warning(&format!(
                    "queries.rs was generated by sparrow {existing_hash} but you are running \
                     {binary_hash}. Regenerating…"
                ));
            }
        }
    }

    // ── Handle --debug-codegen ────────────────────────────────────────────
    if debug_codegen {
        build::ensure_sparrow_repo_cached().await?;
        build::prepare_instance_workspace(project, instance_name).await?;
        let (code, _) = build::compile_to_string(project, instance_name)?;
        let debug_header = "// ⚠ DEBUG — UNVALIDATED OUTPUT — do not use in production\n\
                            // Generated with --debug-codegen. Run `sparrow check` for validated output.\n";
        fs::create_dir_all(final_queries_rs.parent().ok_or_else(|| eyre::eyre!("queries.rs path has no parent directory"))?)?;
        fs::write(&final_queries_rs, format!("{debug_header}{code}"))?;
        crate::output::success(&format!("Debug output written to {}", final_queries_rs.display()));
        op.success();
        return Ok(());
    }

    // ── Stage 0: HQL analysis ─────────────────────────────────────────────
    let mut syntax_step = Step::with_messages("Validating HQL", "HQL valid");
    syntax_step.start();

    build::ensure_sparrow_repo_cached().await?;
    build::prepare_instance_workspace(project, instance_name).await?;

    let compile_result = build::compile_to_string(project, instance_name);
    let (generated_code, metrics_data) = match compile_result {
        Ok(v) => v,
        Err(e) => {
            syntax_step.fail();
            op.failure();
            return Err(e);
        }
    };
    syntax_step.done_with_info(&format!("{} queries", metrics_data.num_of_queries));

    // ── Stage 1: Generator self-assertions ───────────────────────────────
    let mut assert_step = Step::with_messages("Running codegen assertions", "Assertions passed");
    assert_step.start();
    if let Err(e) = check_codegen_assertions(&generated_code) {
        assert_step.fail();
        op.failure();
        return Err(e);
    }
    assert_step.done();

    // ── Stage 2: cargo check in hermetic workspace ────────────────────────
    let cargo_check_src = instance_workspace
        .join("sparrow-repo-copy/crates/sparrow-container/src");
    let sparrow_container_dir = instance_workspace
        .join("sparrow-repo-copy/crates/sparrow-container");
    let check_target_dir = project.sparrow_dir.join("check-cache");

    ensure_hermetic_workspace(&instance_workspace.join("sparrow-repo-copy")).await?;

    // Snapshot originals (restore unconditionally afterwards)
    let original_queries = fs::read(cargo_check_src.join("queries.rs")).ok();
    let original_config = fs::read(cargo_check_src.join("config.hx.json")).ok();

    // Copy config.hx.json from instance src dir (written by compile_to_string)
    let instance_src_dir = instance_workspace.join("sparrow-container/src");
    if instance_src_dir.join("config.hx.json").exists() {
        fs::copy(
            instance_src_dir.join("config.hx.json"),
            cargo_check_src.join("config.hx.json"),
        )?;
    }

    // Write generated code to temp file, then place it where cargo check expects it
    let temp_queries = cargo_check_src.join("queries.rs.tmp");
    fs::write(&temp_queries, &generated_code)?;
    fs::copy(&temp_queries, cargo_check_src.join("queries.rs"))?;

    let mut cargo_step = Step::with_messages("Running cargo check", "Cargo check passed");
    cargo_step.start();
    Step::verbose_substep("Running cargo check on generated code…");

    let cargo_result = run_cargo_check(&sparrow_container_dir, &check_target_dir).await;

    // Restore sparrow-repo-copy originals regardless of cargo check outcome
    match original_queries {
        Some(content) => {
            if let Err(e) = fs::write(cargo_check_src.join("queries.rs"), &content) {
                print_warning(&format!("Failed to restore queries.rs in repo copy: {e}"));
            }
        }
        None => { let _ = fs::remove_file(cargo_check_src.join("queries.rs")); }
    }
    match original_config {
        Some(content) => {
            if let Err(e) = fs::write(cargo_check_src.join("config.hx.json"), &content) {
                print_warning(&format!("Failed to restore config.hx.json: {e}"));
            }
        }
        None => { let _ = fs::remove_file(cargo_check_src.join("config.hx.json")); }
    }
    let _ = fs::remove_file(&temp_queries);

    let compile_time = start_time.elapsed().as_secs() as u32;
    let cargo_output = cargo_result?;

    if !cargo_output.success {
        cargo_step.fail();
        op.failure();

        metrics_sender.send_compile_event(
            instance_name.to_string(),
            metrics_data.queries_string,
            metrics_data.num_of_queries,
            compile_time,
            false,
            Some(cargo_output.errors_only.clone()),
        );

        let attributed = attribute_cargo_errors(&cargo_output.errors_only, &generated_code);
        eprintln!("{attributed}");
        return Err(eyre::eyre!("sparrow check failed: codegen produced invalid Rust"));
    }

    cargo_step.done();

    // ── Stage 3: Atomic rename with version stamp ─────────────────────────
    let stamped_code = prepend_version_stamp(&generated_code);
    fs::create_dir_all(final_queries_rs.parent().ok_or_else(|| eyre::eyre!("queries.rs path has no parent directory"))?)?;
    let final_tmp = final_queries_rs.with_extension("rs.new");
    fs::write(&final_tmp, &stamped_code)?;
    fs::rename(&final_tmp, &final_queries_rs)?;

    metrics_sender.send_compile_event(
        instance_name.to_string(),
        metrics_data.queries_string,
        metrics_data.num_of_queries,
        compile_time,
        true,
        None,
    );

    op.success();
    Ok(())
}

async fn check_all_instances(
    project: &ProjectContext,
    metrics_sender: &MetricsSender,
    debug_codegen: bool,
) -> Result<()> {
    let instances: Vec<String> = project
        .config
        .list_instances()
        .into_iter()
        .map(String::from)
        .collect();

    if instances.is_empty() {
        return Err(eyre::eyre!(
            "No instances found in sparrow.toml. Add at least one instance to check."
        ));
    }

    for instance_name in &instances {
        check_instance(project, instance_name, metrics_sender, debug_codegen).await?;
    }

    crate::output::success("All instances checked successfully");
    Ok(())
}

/// Validate project syntax by parsing queries and schema (similar to build.rs but without generating files)
#[allow(dead_code)]
fn validate_project_syntax(project: &ProjectContext) -> Result<()> {
    // Collect all .hx files for validation
    let hx_files = collect_hx_files(&project.root, &project.config.project.queries)?;

    // Generate content and validate using sparrow-db parsing logic
    let content = generate_content(&hx_files)?;
    let source = parse_content(&content)?;

    // Check if schema is empty before analyzing
    if source.schema.is_empty() {
        let error = crate::errors::CliError::new("no schema definitions found in project")
            .with_context("searched all .hx files in the queries directory but found no N:: (node) or E:: (edge) definitions")
            .with_hint("add at least one schema definition like 'N::User { name: String }' to your .hx files");
        return Err(eyre::eyre!("{}", error.render()));
    }

    // Run static analysis to catch validation errors
    analyze_source(source, &content.files)?;

    Ok(())
}

/// Run cargo check on the generated code.
///
/// `target_dir` is a shared, persistent directory (`.sparrow/check-cache`)
/// reused across all `sparrow check` invocations so dependency artifacts are
/// not recompiled from scratch on every run.
async fn run_cargo_check(sparrow_container_dir: &Path, target_dir: &Path) -> Result<CargoCheckOutput> {
    let output = Command::new("cargo")
        .arg("check")
        .arg("--color=never") // Disable color codes for cleaner output
        .arg("--target-dir")
        .arg(target_dir)
        .current_dir(sparrow_container_dir)
        .output()
        .await
        .map_err(|e| eyre::eyre!("Failed to run cargo check: {}", e))?;

    let stdout = String::from_utf8_lossy(&output.stdout).to_string();
    let stderr = String::from_utf8_lossy(&output.stderr).to_string();
    // stderr contains the actual errors, stdout has JSON if using message-format
    let full_output = format!("{}\n{}", stderr, stdout);

    // Capture error lines and their associated "  -->" location lines.
    // attribute_cargo_errors() uses the "--> src/queries.rs:N:M" lines to
    // find the Rust line number, then scans backward for a sparrow:query= marker.
    let errors_only: String = {
        let lines: Vec<&str> = stderr.lines().collect();
        let mut out = Vec::new();
        for (i, line) in lines.iter().enumerate() {
            if line.starts_with("error") {
                out.push(*line);
                // Include the immediately following " --> " location line if present
                if let Some(next) = lines.get(i + 1) {
                    if next.trim_start().starts_with("-->") {
                        out.push(*next);
                    }
                }
            }
        }
        out.join("\n")
    };

    Ok(CargoCheckOutput {
        success: output.status.success(),
        full_output,
        errors_only,
    })
}

/// Stage 1: scan generated Rust code for known-bad structural patterns.
///
/// Runs in-process at ~0ms. Catches known codegen bug classes before paying
/// the 30–60s cargo check penalty.
///
/// If this fires, it means a known bug has regressed. The error message
/// explicitly attributes it as a SparrowDB bug so the user knows not to
/// fix their HQL.
fn check_codegen_assertions(code: &str) -> Result<()> {
    // Assertion 1: n_from_index key must not be a `.clone()` expression.
    // The key parameter is the third argument (after two string literals).
    // A quick scan: find every "n_from_index(" and check if the rest of
    // the call (up to the closing paren) contains ".clone()".
    for (line_num, line) in code.lines().enumerate() {
        let line_num = line_num + 1;
        if let Some(idx) = line.find("n_from_index(") {
            let after = &line[idx..];
            // Find the third comma (separating third arg from second)
            let mut comma_count = 0;
            let mut third_arg_start = None;
            for (i, ch) in after.char_indices() {
                if ch == ',' {
                    comma_count += 1;
                    if comma_count == 2 {
                        third_arg_start = Some(i + 1);
                        break;
                    }
                }
            }
            if let Some(start) = third_arg_start {
                let third_arg = &after[start..];
                if third_arg.contains(".clone()") {
                    return Err(eyre::eyre!(
                        "codegen bug [Stage 1 assertion]: n_from_index key argument contains \
                         .clone() on line {line_num}.\n\
                         This means the WHERE optimizer emitted an owned value instead of a \
                         reference for the index key.\n\
                         This is a SparrowDB bug. Please report with your .hx files at: \
                         https://github.com/SparrowDB/sparrowdb/issues\n\
                         Run `sparrow check --debug-codegen` to inspect the full generated output."
                    ));
                }
            }
        }

        // Assertion 2: no UNKNOWN GeneratedValue placeholders.
        if line.contains("/* UNKNOWN */") || line.contains("\"UNKNOWN\"") {
            return Err(eyre::eyre!(
                "codegen bug [Stage 1 assertion]: unknown GeneratedValue on line {line_num}.\n\
                 The code generator produced a placeholder instead of a real Rust expression.\n\
                 This is a SparrowDB bug. Please report with your .hx files at: \
                 https://github.com/SparrowDB/sparrowdb/issues\n\
                 Run `sparrow check --debug-codegen` to inspect the full generated output."
            ));
        }
    }
    Ok(())
}

/// Handle cargo check failure - print errors and offer GitHub issue creation.
#[allow(dead_code)]
fn handle_cargo_check_failure(
    cargo_output: &CargoCheckOutput,
    _generated_rust: &str,
    _project: &ProjectContext,
) -> Result<()> {
    print_error("Cargo check failed on generated Rust code");
    println!();

    if !cargo_output.errors_only.is_empty() {
        eprintln!("{}", cargo_output.errors_only);
        println!();
    }

    println!("This may indicate a bug in the SparrowDB code generator.");
    println!();

    print_warning("Please report this issue at https://github.com/SparrowDB/sparrowdb/issues");

    Ok(())
}

/// Check whether the sparrow-repo-copy workspace is pinned to the binary's commit hash.
/// Attempts git checkout to the binary hash if there is a mismatch.
///
/// Uses tokio::process::Command — safe to call from async context.
async fn ensure_hermetic_workspace(sparrow_repo_copy_dir: &std::path::Path) -> Result<()> {
    let binary_hash = env!("SPARROW_BUILD_HASH");
    if binary_hash == "unknown" {
        print_warning(
            "SPARROW_BUILD_HASH is 'unknown' — workspace hermetic pinning skipped."
        );
        return Ok(());
    }

    let repo_path_str = sparrow_repo_copy_dir
        .to_str()
        .ok_or_else(|| eyre::eyre!("sparrow-repo-copy path is not valid UTF-8"))?;

    let head_output = Command::new("git")
        .args(["-C", repo_path_str, "rev-parse", "--short=7", "HEAD"])
        .output()
        .await
        .map_err(|e| eyre::eyre!("Failed to read sparrow-repo-copy HEAD: {e}"))?;

    if !head_output.status.success() {
        // Not a git repo — skip pinning
        return Ok(());
    }

    let current_head = String::from_utf8_lossy(&head_output.stdout).trim().to_string();

    // Extract the commit hash from binary_hash.
    //
    // `git describe --always --dirty` produces strings like:
    //   "v3.0.0-222-g06e9093f"        (tagged build, commit prefix with 'g')
    //   "v3.0.0-222-g06e9093f-dirty"  (tagged build, uncommitted changes)
    //   "06e9093f"                      (no tag reachable)
    //
    // The hash segment is prefixed with 'g' when a tag is present. Strip that
    // prefix before the hex check so the extraction works in both forms.
    let binary_short = binary_hash
        .split('-')
        .find_map(|part| {
            // Strip the optional 'g' prefix that git describe adds before the hash.
            let h = part.strip_prefix('g').unwrap_or(part);
            (h.len() >= 7 && h.chars().all(|c| c.is_ascii_hexdigit())).then_some(h)
        })
        .unwrap_or(binary_hash);

    // Accept if either abbreviation is a prefix of the other: git rev-parse --short=7
    // returns 7 chars while git describe may embed 8+ char hashes, but both refer
    // to the same commit when one starts with the other.
    if current_head == binary_short
        || binary_short.starts_with(current_head.as_str())
        || current_head.starts_with(binary_short)
    {
        return Ok(());
    }

    print_warning(&format!(
        "sparrow-repo-copy is at {current_head} but binary is {binary_hash}. \
         Checking out {binary_short} for hermetic cargo check…"
    ));

    // Checkout the extracted short hash, not the full git describe string (which
    // includes tags and the -dirty suffix and is not a valid git ref).
    let checkout = Command::new("git")
        .args(["-C", repo_path_str, "checkout", binary_short])
        .output()
        .await
        .map_err(|e| eyre::eyre!("Failed to checkout {binary_short}: {e}"))?;

    if !checkout.status.success() {
        print_warning(&format!(
            "Could not checkout {binary_short} in sparrow-repo-copy. cargo check may not be hermetic."
        ));
    }
    Ok(())
}

/// Attribute cargo check errors back to their HQL source using
/// `// sparrow:query=NAME source=FILE:LINE` markers in the generated code.
fn attribute_cargo_errors(errors_only: &str, generated_code: &str) -> String {
    let code_lines: Vec<&str> = generated_code.lines().collect();
    let mut attributed = Vec::new();

    for error_line in errors_only.lines() {
        // Cargo error lines contain: "... --> src/queries.rs:42:5"
        let line_num: Option<usize> = error_line
            .split("queries.rs:")
            .nth(1)
            .and_then(|s| s.split(':').next())
            .and_then(|n| n.parse::<usize>().ok());

        let query_attr = line_num.and_then(|n| {
            let idx = n.saturating_sub(1);
            code_lines[..idx.min(code_lines.len())]
                .iter()
                .rev()
                .find(|l| l.contains("// sparrow:query="))
                .map(|l| l.trim().to_string())
        });

        match query_attr {
            Some(marker) => {
                let name = marker
                    .split("sparrow:query=").nth(1)
                    .and_then(|s| s.split_whitespace().next())
                    .unwrap_or("unknown");
                let source = marker
                    .split("source=").nth(1)
                    .unwrap_or("unknown");
                attributed.push(format!(
                    "codegen bug in query '{name}' ({source}):\n  {error_line}\n  \
                     This is a SparrowDB bug. Run `sparrow check --debug-codegen` to inspect output."
                ));
            }
            None => {
                attributed.push(format!(
                    "likely a codegen bug (no query marker found):\n  {error_line}"
                ));
            }
        }
    }
    attributed.join("\n")
}

#[cfg(test)]
mod stamp_tests {
    use super::*;

    #[test]
    fn prepend_version_stamp_adds_header() {
        let stamped = prepend_version_stamp("fn main() {}");
        assert!(stamped.starts_with("// generated by sparrow "));
        assert!(stamped.contains("// sparrow-core workspace: "));
        assert!(stamped.contains("// Do not edit"));
        assert!(stamped.ends_with("fn main() {}"));
    }

    #[test]
    fn read_existing_stamp_hash_parses_first_line() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("queries.rs");
        std::fs::write(&path, "// generated by sparrow abc1234-dirty\nfn main() {}").unwrap();
        let hash = read_existing_stamp_hash(&path);
        assert_eq!(hash, Some("abc1234-dirty".to_string()));
    }

    #[test]
    fn read_existing_stamp_hash_returns_none_for_unstamped() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("queries.rs");
        std::fs::write(&path, "// auto-generated\nfn main() {}").unwrap();
        let hash = read_existing_stamp_hash(&path);
        assert_eq!(hash, None);
    }
}

#[cfg(test)]
mod assertion_tests {
    use super::*;

    #[test]
    fn assertion_passes_on_clean_code() {
        let code = r#"
pub fn get_user(input: HandlerInput) -> Result<Response, GraphError> {
    // sparrow:query=GetUser source=users.hx:1
    let db = Arc::clone(&input.graph.storage);
    let r = db.n_from_index("User", "slug", &data.slug);
}
"#;
        assert!(check_codegen_assertions(code).is_ok());
    }

    #[test]
    fn assertion_catches_clone_in_n_from_index() {
        let code = r#"
    let r = db.n_from_index("User", "slug", data.slug.clone());
"#;
        let result = check_codegen_assertions(code);
        assert!(result.is_err(), "Expected assertion error for .clone() in n_from_index");
        assert!(result.unwrap_err().to_string().contains("n_from_index"));
    }

    #[test]
    fn assertion_catches_unknown_generated_value() {
        let code = r#"
    let val = /* UNKNOWN */;
"#;
        let result = check_codegen_assertions(code);
        assert!(result.is_err(), "Expected assertion error for UNKNOWN generated value");
    }
}
