//! sparrow doctor — pre-flight health checklist.
//!
//! Runs in under 2 seconds. No cargo invocations.
//! Exit code 0 on success, 1 if any blocking check fails.

use crate::project::ProjectContext;
use eyre::Result;
use tokio::process::Command;

pub struct CheckResult {
    pub label: String,
    pub ok: bool,
    pub detail: String,
    pub hint: Option<String>,
    pub blocking: bool,
    pub skipped: Option<String>,
}

pub async fn run(json: bool) -> Result<()> {
    let mut results: Vec<CheckResult> = Vec::new();

    // Check 1: CLI version (informational)
    results.push(CheckResult {
        label: "CLI".to_string(),
        ok: true,
        detail: format!(
            "sparrow v{} ({})",
            env!("CARGO_PKG_VERSION"),
            env!("SPARROW_BUILD_HASH")
        ),
        hint: None,
        blocking: false,
        skipped: None,
    });

    // Load project context for instance-level checks (best effort — not an error if missing)
    let project = ProjectContext::find_and_load(None).ok();

    // Check 2: queries.rs in sync with CLI (per instance)
    if let Some(ref project) = project {
        let binary_hash = env!("SPARROW_BUILD_HASH");
        let instances = project.config.list_instances();
        if instances.is_empty() {
            results.push(CheckResult {
                label: "queries.rs".to_string(),
                ok: true,
                detail: "no instances configured".to_string(),
                hint: None,
                blocking: false,
                skipped: None,
            });
        }
        for instance_name in &instances {
            let instance_workspace = project.instance_workspace(instance_name);
            let queries_rs = instance_workspace.join("sparrow-container/src/queries.rs");
            let (ok, detail, hint) = if binary_hash == "unknown" {
                (true, "version unknown — skipping hash comparison".to_string(), None)
            } else {
                match crate::commands::check::read_existing_stamp_hash_pub(&queries_rs) {
                    Some(h) if h == binary_hash => (
                        true,
                        format!("in sync with CLI ({h})"),
                        None,
                    ),
                    Some(h) => (
                        false,
                        format!("generated by sparrow {h}, CLI is {binary_hash}"),
                        Some("Run `sparrow check` to regenerate.".to_string()),
                    ),
                    None => (
                        false,
                        "no version stamp — run `sparrow check` first".to_string(),
                        Some("Run `sparrow check`.".to_string()),
                    ),
                }
            };
            results.push(CheckResult {
                label: format!("queries.rs ({instance_name})"),
                ok,
                detail,
                hint,
                blocking: true,
                skipped: None,
            });
        }
    } else {
        results.push(CheckResult {
            label: "queries.rs".to_string(),
            ok: true,
            detail: "no sparrow.toml found — skipping".to_string(),
            hint: None,
            blocking: false,
            skipped: None,
        });
    }

    // Check 3: Cached workspace HEAD (informational — affects hermetic validation)
    results.push(check_cached_workspace().await);

    // Checks 4 + 5 run in parallel (Docker + instance health)
    let docker_future = check_docker();
    let instances_future = check_instances(&project);
    let (docker_result, mut instance_results) = tokio::join!(docker_future, instances_future);

    let docker_running = docker_result.ok;
    results.push(docker_result);

    // Instance health: skip if Docker not running
    if !docker_running {
        for mut r in instance_results.drain(..) {
            r.skipped = Some("Docker not available".to_string());
            results.push(r);
        }
    } else {
        results.extend(instance_results);
    }

    // Print or serialize
    if json {
        print_json(&results);
    } else {
        print_human(&results);
    }

    let has_blocking_failure = results.iter().any(|r| r.blocking && !r.ok && r.skipped.is_none());
    if has_blocking_failure {
        std::process::exit(1);
    }
    Ok(())
}

async fn check_cached_workspace() -> CheckResult {
    let binary_hash = env!("SPARROW_BUILD_HASH");
    if binary_hash == "unknown" {
        return CheckResult {
            label: "Cached workspace".to_string(),
            ok: true,
            detail: "version unknown — skipping".to_string(),
            hint: None,
            blocking: false,
            skipped: None,
        };
    }
    let cache_path = match crate::project::get_sparrow_repo_cache() {
        Ok(p) => p,
        Err(_) => {
            return CheckResult {
                label: "Cached workspace".to_string(),
                ok: false,
                detail: "could not determine cache path".to_string(),
                hint: Some("Run `sparrow build` to create the cache.".to_string()),
                blocking: true,
                skipped: None,
            };
        }
    };
    if !cache_path.exists() {
        return CheckResult {
            label: "Cached workspace".to_string(),
            ok: false,
            detail: "not present".to_string(),
            hint: Some("Run `sparrow build` to create the cache.".to_string()),
            blocking: true,
            skipped: None,
        };
    }
    let head = Command::new("git")
        .args(["-C", &cache_path.to_string_lossy(), "rev-parse", "--short=7", "HEAD"])
        .output()
        .await;
    match head {
        Ok(o) if o.status.success() => {
            let head_str = String::from_utf8_lossy(&o.stdout).trim().to_string();
            let pinned = binary_hash.starts_with(&head_str) || binary_hash == head_str;
            CheckResult {
                label: "Cached workspace".to_string(),
                ok: pinned,
                detail: if pinned {
                    format!("present and pinned to {head_str}")
                } else {
                    format!("at {head_str}, binary is {binary_hash}")
                },
                hint: if pinned {
                    None
                } else {
                    Some("Run `sparrow check` to re-pin the workspace.".to_string())
                },
                blocking: !pinned,
                skipped: None,
            }
        }
        _ => CheckResult {
            label: "Cached workspace".to_string(),
            ok: false,
            detail: "could not read cache HEAD".to_string(),
            hint: Some("Run `sparrow build` to recreate the cache.".to_string()),
            blocking: true,
            skipped: None,
        },
    }
}

async fn check_docker() -> CheckResult {
    let result = Command::new("docker").arg("info").output().await;
    match result {
        Ok(o) if o.status.success() => CheckResult {
            label: "Docker".to_string(),
            ok: true,
            detail: "daemon running".to_string(),
            hint: None,
            blocking: false,
            skipped: None,
        },
        _ => CheckResult {
            label: "Docker".to_string(),
            ok: false,
            detail: "daemon not running".to_string(),
            hint: Some(
                "Start Docker Desktop or Podman before running `sparrow push`.".to_string(),
            ),
            blocking: true,
            skipped: None,
        },
    }
}

async fn check_instances(project: &Option<ProjectContext>) -> Vec<CheckResult> {
    let Some(project) = project else {
        return vec![];
    };
    let instances = project.config.list_instances();
    let mut results = Vec::new();
    for instance_name in &instances {
        let instance_config = match project.config.get_instance(instance_name) {
            Ok(c) => c,
            Err(_) => continue,
        };
        let port = instance_config.port().unwrap_or(6969);
        let url = format!("http://localhost:{port}/diagnostics");
        let result = match reqwest::Client::new()
            .get(&url)
            .timeout(std::time::Duration::from_secs(2))
            .send()
            .await
        {
            Ok(resp) if resp.status().is_success() => {
                let body = resp.text().await.unwrap_or_default();
                let nodes: Option<u64> = serde_json::from_str::<serde_json::Value>(&body)
                    .ok()
                    .and_then(|v| v["nodes"].as_u64());
                CheckResult {
                    label: format!("Instance '{instance_name}'"),
                    ok: true,
                    detail: match nodes {
                        Some(n) => format!("running on :{port} — {n} nodes"),
                        None => format!("running on :{port}"),
                    },
                    hint: None,
                    blocking: false,
                    skipped: None,
                }
            }
            _ => CheckResult {
                label: format!("Instance '{instance_name}'"),
                ok: false,
                detail: format!("not found on :{port}"),
                hint: Some(format!("Run `sparrow push {instance_name}` to deploy.")),
                blocking: false,
                skipped: None,
            },
        };
        results.push(result);
    }
    results
}

pub fn print_human(results: &[CheckResult]) {
    println!();
    let mut issues = 0;
    for r in results {
        if let Some(skip_reason) = &r.skipped {
            println!("  ? skipped: {}", skip_reason);
            continue;
        }
        if r.ok {
            println!("  ✓ {}: {}", r.label, r.detail);
        } else {
            println!("  ✗ {}: {}", r.label, r.detail);
            if let Some(hint) = &r.hint {
                println!("      → {hint}");
            }
            if r.blocking {
                issues += 1;
            }
        }
    }
    println!();
    if issues > 0 {
        println!("  {issues} blocking issue(s) found. Fix the ✗ items above before deploying.");
    } else {
        println!("  All checks passed.");
    }
    println!();
}

pub fn print_json(results: &[CheckResult]) {
    let obj: Vec<serde_json::Value> = results
        .iter()
        .map(|r| {
            serde_json::json!({
                "label": r.label,
                "ok": r.ok,
                "detail": r.detail,
                "blocking": r.blocking,
                "hint": r.hint,
                "skipped": r.skipped,
            })
        })
        .collect();
    println!(
        "{}",
        serde_json::to_string_pretty(&serde_json::Value::Array(obj)).unwrap()
    );
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn print_human_does_not_panic_on_empty() {
        print_human(&[]);
    }

    #[test]
    fn print_human_shows_tick_for_ok() {
        let results = vec![CheckResult {
            label: "CLI".to_string(),
            ok: true,
            detail: "sparrow v3.0.0 (abc1234)".to_string(),
            hint: None,
            blocking: false,
            skipped: None,
        }];
        // Just verify no panic
        print_human(&results);
    }

    #[test]
    fn print_json_valid_json() {
        let results = vec![CheckResult {
            label: "Docker".to_string(),
            ok: false,
            detail: "daemon not running".to_string(),
            hint: Some("Start Docker Desktop.".to_string()),
            blocking: true,
            skipped: None,
        }];
        // Just verify no panic
        print_json(&results);
    }
}
